name: Update production branch ðŸš¨

on: workflow_call

jobs:
  deploy:
    uses: pressbooks/reusable-workflows/.github/workflows/after-release.yml@dev
    secrets:
      ga_token: ${{ secrets.GITHUB_TOKEN }}
